### ISSUE TITLE
Not working with new Gorm 6.1 in Grails 3.3

### ISSUE THREAD

**Issue by virtualdogbert** [virtualdogbert/Enforcer#13]
Unable to produce AST for this phase due to earlier compilation error:
startup failed:
script1509283741398.groovy: 34: [Static type checking] - The variable [sp] is undeclared.
 @ line 34, column 25.
       @Enforce({isCreator(sp)})
                           ^

script1509283741398.groovy: 34: [Static type checking] - Cannot find matching method com.security.TestService#isCreator(java.lang.Object). Please check if the declared type is right and if the method exists.
 @ line 34, column 15.
       @Enforce({isCreator(sp)})
                 ^

2 errors

Fix the above error(s) and then press Refresh

My feealing after looking at the code, I think that this is the line that is biting me:
https://github.com/grails/grails-data-mapping/blob/master/grails-datastore-gorm/src/main/groovy/org/grails/datastore/gorm/transform/AbstractMethodDecoratingTransformation.groovy#L225

**Comment by virtualdogbert** [comment]
So I figured out a way to fix this, however I get the same Error with @CompileStatic, which I asked Paul King about at the G3 Summit, hopefully he'll have some time to take a look. I'm thinking a workaround maybe figuring out how to use type check extensions to tell the compiler to ignore the issue.

**Comment by virtualdogbert** [comment]
virtualdogbert [9:25 PM]
Does anyone know if there is a way with an AST transform to remove/delete an annotation, so that further AST transforms won't see it(ji.e. @CompileStatic)? What I have is an AST transform that creates some code, however with changes to @CompileStatic, it no longer plays well with it, because it takes a closure as a parameter, and @CompileStatic is throwing errors, because of that.  

I am also trying to play around with the type extensions, but I haven't had any luck and I haven't figured out how to debug them.

I have asked Paul, but he's too busy with 2.5, and I have a feeling that once he finished 2.5, he'll be too busy with 3.0, which is cool. I wish there were more people who have a deep knowledge of AST transforms, or I just knew who they were... (edited)


paulk_asert [11:04 PM]
Annotations themselves are just handled at the ClassNode level - but the list of transformations that will be processed is calculated up front.

virtualdogbert [11:22 PM]
Ok thanks. That makes me think removal would be a deadend, so the only option at the moment , that I know of would be the type handling extensions. So I'll spend some time playing with that.

**Comment by virtualdogbert** [comment]
The type extensions don't seem as viable as I want them to be. I'm thinking of taking inspiration from my problem @Transactional , which add a proxy call and statically compiles that. So I'm thinking that I create new annotations for Enforcer:

- EnforcerT - creates a proxy method that is dynamic, and a renamed method, that is Transactional.
- EnforcerS  - creates a proxy method that is dynamic, and a renamed method, that is statically compiled.
- EnforcerTS - creates a proxy method that is dynamic, and a renamed method, that is Transactional and statically compiled.

**Comment by virtualdogbert** [comment]
Got the workaround implemented, and committed up.
